# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b71f63ed278b5f9907c34edcedbe961bb9e620e7806d61433d2afbfe39388f2fe2c84acf514e2578b5837c86fd954aa733f98fb91b542f62a6afee97652ca370

test:
  secret_key_base: a813819be30ab97a71fa6179662816f3bcbbe95547dff36f82fe9876c78c47934e70e580a96a1b0de90fbcd423778d43a775ff3a2f2fd74f57c8dd0060da43fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
